### ISSUE TITLE
How to recieve cursor

### ISSUE THREAD

**Issue by lanetteamkaushal** [czyrux/MvpLoaderSample#12]
Hello All !

I just started MVP in android.
I want to create adapter from cursor so How to get cursor from onLoadFinished(Loader<P> loader, P presenter) ?

Thanks,
Kaushlendra.

**Comment by lanetteamkaushal** [comment]
May be my question is not clear. How can I get cursor here.

[PresenterLoader](https://github.com/czyrux/MvpLoaderSample/blob/master/app/src/main/java/de/czyrux/mvploadersample/base/PresenterLoader.java#L38l)

**Comment by czyrux** [comment]
Not really sure that I get your use case. What do you want to achieve? Why do you want a cursor there? The loader used in [PresenterLoader](https://github.com/czyrux/MvpLoaderSample/blob/master/app/src/main/java/de/czyrux/mvploadersample/base/PresenterLoader.java#L7)  is just the mechanism to preserve an object (the Presenter in this case) across orientation changes.

**Comment by lanetteamkaushal** [comment]
Hi @czyrux ,

I want to show data from ContentProvider and I need cursor for that.but I think I might find what I looking for.
[From Google Sample](https://github.com/googlesamples/android-architecture/tree/todo-mvp-contentproviders)

Thanks,
