### ISSUE TITLE
onStart in BasePresenterFragment

### ISSUE THREAD

**Issue by ochkarik05** [czyrux/MvpLoaderSample#2]
In BasePresenterFragment you do:

```
 @Override
    public void onStop() {
        presenter.onViewDetached();
        super.onStop();
        Log.i(TAG, "onPause-" + tag());
    }
```

But what about attaching the view back in onStart() method? 
I think it should be like that:

```
 @Override
    public void onStop() {
    if(presenter != null){        
        presenter.onViewDetached();
    }
        super.onStop();
        Log.i(TAG, "onStop-" + tag());
    }
```

```
    @Override
    public void onStart() {
        super.onStart();
        if(presenter != null){
             presenter.onViewAttached(getPresenterView());
       }
        Log.i(TAG, "onStart-" + tag());
    }

```

**Comment by czyrux** [comment]
As mention in the [post](https://medium.com/@czyrux/presenter-surviving-orientation-changes-with-loaders-6da6d86ffbbf#.rdlskk349), you cannot rely that by the time onStart is reach on fragments the presenter has been delivered. The Presenter will be ready in onStart when the Fragment is first created but between onStart and onResume on orientation changes. (you can check the logs to see such behaviour)

I will add some additional comment to clarify such issue.

**Comment by ochkarik05** [comment]
OK, maybe you are right. It's something completely wrong in my app with loaders.

```
03-20 21:43:55.935 24728-24728 I/base-fragment: onActivityCreated-CalendarFragment
03-20 21:43:55.937 24728-24728 I/base-fragment: onCreateLoader-CalendarFragment
03-20 21:43:55.937 24728-24728 I/loader: onStartLoading-CalendarFragment
03-20 21:43:55.937 24728-24728 I/loader: onForceLoad-CalendarFragment
03-20 21:43:55.941 24728-24728 I/base-fragment: onLoadFinished-CalendarFragment
03-20 21:43:55.942 24728-24728 I/base-fragment: onStart-CalendarFragment
03-20 21:44:04.605 24728-24728 I/base-fragment: onStop-CalendarFragment
03-20 21:44:04.616 24728-24728 I/loader: onStopLoading-CalendarFragment
03-20 21:44:22.555 24728-24728 I/loader: onStartLoading-CalendarFragment
03-20 21:44:22.555 24728-24728 I/base-fragment: onStart-CalendarFragment
```

As you can see, after switching to another app and return back, onStartLoading calls for CalendarFragment, but onLoadFinished doesn't. I have no idea why.

**Comment by ochkarik05** [comment]
OK, I see that onLoadFinished doesn't call because LoaderManager knows that data (presenter in our case) already have been delivered. But we have view detached because of onStop method was called when app goes to background. So, if presenter is not null, we have to attach view back in onStart method. Make sense?

**Comment by czyrux** [comment]
Yes, sorry, _you are absolutely right_. I was just focus on the orientation change scenario and did not cover this other one (i did some modifications after publishing the code playing with the delivering moment).

I will update covering this case. Thanks for reporting!

**Comment by ochkarik05** [comment]
Thank you for great idea, i like it very much. Take my best wishes )
