### ISSUE TITLE
Loader gets reset after returning from "child" Activity

### ISSUE THREAD

**Issue by chriswiesner** [czyrux/MvpLoaderSample#3]
Steps to reproduce:

having an Activity with Presenter-Loader. Loader behaves correctly on orientation change. But:
having the Activity in Portrait, calling/starting another Activity that is forced to landscape and the returning back from this activity lets the Loadermanager reset the loader and the Presenter does not survive.

Has anybody else experienced that issue?

**Comment by chriswiesner** [comment]
just found out that this could be due to: https://code.google.com/p/android/issues/detail?id=200927

which should be fixed in support lib 24.0.0

i'll check that

**Comment by czyrux** [comment]
thanks for reporting and linking the google issue.

Yes, I can confirm that this is an issue and, unfortunately, something that make this approach no so convenient.

Lets keep an eye on the open bug.

**Comment by chriswiesner** [comment]
i can confirm that support lib 24.0.0 fixed the issue.
