### ISSUE TITLE
Possible null Presenter reference

### ISSUE THREAD

**Issue by fmrsabino** [czyrux/MvpLoaderSample#4]
In the [BasePresenterActivity ](https://github.com/czyrux/MvpLoaderSample/blob/master/app/src/main/java/de/czyrux/mvploadersample/base/BasePresenterActivity.java) you call the `initLoader()` on the `onCreate()` method.

When the `onLoadFinished` of that given loader is called you set the `presenter` field with the loaded presenter.

However, you reference the presenter on the `onStart()` method but is there any guarantee that the `onLoadFinished` callback has been executed prior to the `onStart()` method (i.e. do we know for sure that we have a presenter by the time `onStart()` executes)? Thanks!

Edit: On the documentation of the Loader, [startLoading](https://developer.android.com/reference/android/support/v4/content/Loader.html#startLoading%28%29) states that

> This function will normally be called for you automatically by LoaderManager when the associated fragment/activity is being started.

I didn't assume that the state of "being started" corresponded to the onStart() method or equivalent thus my question. And as it is documented it seems that may not always happen. Closing the issue. Thanks!

**Comment by rperryng** [comment]
```
E  Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.taro.android.ui.base.MvpContract$Presenter.onViewAttached(com.taro.android.ui.base.MvpContract$View)' on a null object reference
E      at com.taro.android.ui.base.BaseActivity.onStart(BaseActivity.java:49)
```

I can see in my logs that `onStartLoading` and `onForceLoad` are both called, but not `onLoadFinished`, (`onStart` is being called beforehand).  It seems it is not reliable to assume that the loader has finished by `onStart()`, like the implementation in this project.  Any ideas what the proper way to handle this should be?
